const actiontypes = {
  SET_RANDOM_RESULT: "SET_RANDOM_RESULT",
  SET_GUESS: "SET_GUESS",
  SET_SUCCESS_STATUS: "SET_SUCCESS_STATUS",
  SET_ERROR: "SET_ERROR",
  RESET_ERRORS: "RESET_ERRORS",
  REMOVE_ERROR: "REMOVE_ERROR"
};

export default actiontypes;
